### ISSUE TITLE
Build process does not recover from syntax errors

### ISSUE THREAD

**Issue by guido4000** [cxa/reason-react-webpack-starter-kit#1]
The build process hangs after running into a syntax error. Saving the source after removing the syntax error does not lead to a proper rebuild. The only option is to kill the process and start it from scratch.

Example:
```

 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./index.re

ERROR in ./src/index.re
Module build failed: Error: Command failed: /Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit/node_modules/bs-platform/bin/bsb -make-world
ninja: error: rebuilding 'build.ninja': subcommand failed
Error happened when running command /Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit/node_modules/bs-platform/bin/bsb.exe with args [ '-make-world' ]

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./index.re
webpack: Failed to compile.
^C
````

**Comment by rrdelaney** [comment]
This is most likely an issue with bs-loader and how it handles errors. I'll update this when I know more

**Comment by cxa** [comment]
@guido4000 Update bs-loader to 1.2.1 should fix this issue.

**Comment by guido4000** [comment]
Just tried it with the new version and it still does not recover.

```
[1/2] Building src/welcome.mlast
FAILED: src/welcome.mlast
/Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit2/node_modules/bs-platform/bin/bsc.exe -pp "/Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit2/node_modules/bs-platform/bin/refmt.exe --print binary" -ppx '/Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit2/node_modules/bs-platform/bin/reactjs_jsx_ppx.exe'   -nostdlib -I /Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit2/node_modules/bs-platform/lib/ocaml -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -c -o src/welcome.mlast -bs-syntax-only -bs-binary-ast -impl /Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit2/src/welcome.re
File "/Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit2/src/welcome.re", line 8, characters 6-25:
Syntax error: Start tag <h2> does not match end tag </div>
File "/Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit2/src/welcome.re", line 1:
Error: Error while running external preprocessor
Command line: /Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit2/node_modules/bs-platform/bin/refmt.exe --print binary '/Users/main12/Projects/fun/reason/reason-react-webpack-starter-kit2/src/welcome.re' > /var/folders/fk/8bvbh30d1rg0l40svr5rsbd40000gn/T/ocamlppf628f3


 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./index.re
webpack: Compiled with warnings.
```

**Comment by cxa** [comment]
Should work under bs-loader 1.2.3.

**Comment by guido4000** [comment]
Yes, it's working. Thank you.

**Comment by cxa** [comment]
No problem.
